WIP: Add DebProfile to Profilemanager
candlepin/subscription-manager pull request #2132
Opened 2019-08-05 15:38 UTC by mdellweg

2019-08-05 15:40 UTC, mdellweg commented
Still not even confirmed to work. But i'd be happy to get some feedback on this.

2019-08-08 15:16 UTC, mdellweg commented
@kahowell As i am trying to reuse the repofile.py here, a little bit of restructuring is needed. I would like your :eyes: on this, to know this is going in the right direction.
(atm enabled_repos profile is working for AptRepoFile only, but the others should be repaired by tomorrow.)

2019-08-12 10:32 UTC, mdellweg commented
I think, this is ready for review now.

2019-08-15 13:30 UTC, cnsnyder commented
@mdellweg Overall looks great! I am curious about one thing. Why move repofile to rhsm?

2019-08-15 13:30 UTC, cnsnyder commented
@candlepin-bot ok to test

2019-08-26 08:59 UTC, mdellweg commented
> @mdellweg Overall looks great! I am curious about one thing. Why move repofile to rhsm?

I think the dependency chain is that subman uses rhsm, and since the new code, being part of rhsm and using repofile.py, that code must move up on that chain.

2019-08-26 09:08 UTC, mdellweg commented
@cnsnyder can you tell me a bit more about the test failures, as i cannot access the results.

2019-08-29 17:25 UTC, cnsnyder commented
@candlepin-bot please retest this

2019-09-18 15:04 UTC, mdellweg commented
@cnsnyder rebased due to conflicts.

2019-10-07 06:20 UTC, mdellweg commented
@cnsnyder ^^

2019-11-27 15:35 UTC, jturel commented
@cnsnyder any review feedback for Matthias?

2020-01-16 20:00 UTC, cnsnyder commented
@candlepin-bot Please retest this

2020-01-16 20:31 UTC, cnsnyder commented
@candlepin-bot please retest this

2020-02-11 10:30 UTC, jirihnidek requested changes
Please solve conflicts with master branch.

2020-02-11 10:30 UTC, jirihnidek commented on src/subscription_manager/cache.py
> +        elif "rpm" in combined_profile:
This change of logic has potential to break functionality. Candlepin server cannot have capability "combined_reporting", but it still can be able to have capability of receiving package profile.

2020-02-12 12:44 UTC, mdellweg commented
I have big trouble keeping this PR up in shape. I can not see any results of the tests, and in the meantime something in the Vagrant part must have changed to the point where i can not even provision the centos box.
It would be nice, if someone with access to the ci server logs could take this up, as i do not have the resources to more than the occasionally rebase.

2020-04-08 06:42 UTC, jirihnidek commented
Hi @mdellweg I will take this up. Thanks for this PR.

2020-04-08 07:41 UTC, mdellweg commented
Thank you so much! It would have been a shame to see that work going to waste.

2020-05-11 12:36 UTC, jturel commented
Needs rebase :)

2020-10-22 12:23 UTC, m-bucher commented
@mdellweg @jirihnidek I did a rebase to the best of my knowledge (which arguably is not much, I am afraid).

Also added a fix to only upload enabled repositories for Debian hosts

2021-07-27 15:24 UTC, wottop commented
This needs a rebase to be considered. If no action is taken on this PR, it will be closed on August 27, 2021.

2021-08-30 14:11 UTC, wottop commented
@m-bucher can you please rebase to main and try the nose and stylish tests locally?

2021-11-09 13:53 UTC, wottop commented
@m-bucher @mdellweg
Can you please follow up with a rebase and then confirm the tests with local runs?
Thanks

2021-12-14 14:17 UTC, wottop commented
@m-bucher @mdellweg
Can you please follow up with a rebase and then confirm the tests with local runs?
Thanks

2021-12-14 14:34 UTC, mdellweg commented
@wottop Sorry, I won't have the capacity to work on this in the forseeable future.

2021-12-21 17:42 UTC, sbernhard commented
Rebased to current main. We want to proceed with this change as it is necessary to have a full-featured debian/ubuntu subscription-manager. 

Please have a look.

2022-01-13 18:04 UTC, ptoscano requested changes
Sorry for the (again) late answer to this PR. I'm afraid I will need to ask for one more round of rebase on top of the current `main` branch.

In addition to that, please start cleaning this work a little bit, so it has less changes and it is easier to review:
- please avoid extra changes to the debug lines
- many `open()` calls got `encoding='utf-8'`, which I don't understand what it should do in the context of the proposed changes
- there was an recent-ish comment by @jirihnidek that I don't see addressed or explained
- please squash the commits with fixups together to the commits that they fix, otherwise there are broken commits in the history (which makes bisection and regression checking in general harder)
- please also improve the commit messages & the description of this PR: it is hard to understand why certain changes were done, and in general what is the final goal; yes, I can imagine it seems "logic" as it is already, however it will not be that much in 1 years/5 years/etc, making it harder to other developers to figure out *why* something was done

In any case, thanks again for the patience on this, and looking forward to a newer version!

2022-01-14 17:10 UTC, bastian-src commented
The debug line and enconding changes regarding `open` were introduced due to pylint warnings on both of these. I've dropped the last commit which introduced those changes.
Thanks for the feedback on this, your other comments are gonna be worked on soon!

2022-03-09 21:27 UTC, cnsnyder commented
@bastian-src Hi! I hope this note finds you well! Is there anything we can do to help out on these changes? If there is still more to be done and it will take some time could we close this PR and open a new one once the changes have been complete?

2022-04-07 14:59 UTC, cnsnyder commented
@bastian-src Thank you for all your work on this PR! We'd really like to include this in subscription-manager at some point in the future! Since it's been about a month since there have been updates we will close this PR for the time being. When there are again updates to this branch based on the above feedback, please feel free to update this branch and repopen this PR (or if it makes more sense, feel free to open a new PR).

2022-04-07 14:59 UTC, closed without merging