Jhnidek/ent 3191 collect cloud metadata
candlepin/subscription-manager pull request #2381
Opened 2021-01-05 16:01 UTC by jirihnidek

2021-01-07 18:51 UTC, wottop commented
Result of suggested smoke test:
http://pastebin.test.redhat.com/929683

2021-01-07 18:51 UTC, wottop requested changes

2021-01-07 18:51 UTC, wottop commented on src/rhsmlib/cloud/providers/aws.py
> -# sudo PYTHONPATH=./src:./syspurse/src python3 -m rhsmlib.cloud.providers.aws
/syspurpose/

2021-01-07 18:51 UTC, wottop commented on src/rhsmlib/cloud/providers/azure.py
> -# sudo PYTHONPATH=./src:./syspurse/src python3 -m rhsmlib.cloud.providers.azure
/syspurpose/

2021-01-07 18:52 UTC, wottop commented on src/rhsmlib/cloud/providers/aws.py
> +# sudo PYTHONPATH=./src:./syspurse/src python3 -m rhsmlib.cloud.providers.aws
/syspurpose/

2021-01-07 18:53 UTC, wottop commented on src/rhsmlib/cloud/providers/azure.py
> +# sudo PYTHONPATH=./src:./syspurse/src python3 -m rhsmlib.cloud.providers.azure
/syspurpose/

2021-01-07 18:53 UTC, wottop commented on src/rhsmlib/cloud/providers/gcp.py
> +# sudo PYTHONPATH=./src:./syspurse/src python3 -m rhsmlib.cloud.providers.gcp
/syspurpose/

2021-01-08 09:56 UTC, jirihnidek commented
> Result of suggested smoke test:
> http://pastebin.test.redhat.com/929683

Yeah, it is expected result, when you run code on your laptop. The output could be little bit confusing, because I collect system facts first to be able to detect anything and code gathering system facts prints some strange values.

Did you test it on any VM running on AWS/Azure/GCP?

2021-01-08 10:32 UTC, jirihnidek commented on src/rhsmlib/cloud/providers/aws.py
> +        # When it wasn't possible to get metadata using IMDSv1, then try to get metadata using IMDSv2
New version requires three http requests and the IMDSv1 requires only two http requests. Using security token IMHO doesn't provide more security it only adds another http request.

2021-01-08 10:42 UTC, jirihnidek commented on src/rhsmlib/cloud/providers/aws.py
> +    WIP function for smoke testing on AWS cloud
Yeah, I will remove all these `_smoke_test()` functions from `aws.py`, `azure.py` and `gcp.py`, when detecting and collection of metadata will be used by sub-man.

2021-01-08 19:42 UTC, cnsnyder commented
The smoke tests worked for me (turned out true only when running on the requisite cloud platform).

2021-01-18 15:08 UTC, wottop approved these changes

2021-01-25 15:31 UTC, merged