1637083: add unset sections
candlepin/subscription-manager pull request #2493
Opened 2021-03-15 18:50 UTC by tlhmerry9

2021-03-15 18:51 UTC, tlhmerry9 commented
To Test (this branch was created from the subscription-manager-1.28 branch)

man syspurpose/man/syspurpose.8

2021-03-16 10:45 UTC, jirihnidek requested changes
Hi, thanks for PR. I have one comment in the this man page. BTW: We use two very similar words "add-ons" and "addons" for the same thing. Shouldn't we use only "addons"?

2021-03-16 10:45 UTC, jirihnidek commented on syspurpose/man/syspurpose.8
> +Clear set add-ons property
I would write "Clear the system addons property". addons property is a set, but it looks confusing.

2021-03-16 15:30 UTC, jirihnidek commented
Oh, I can see that this PR has conflict too. Please resolve this conflict.

2021-03-16 15:45 UTC, merged

2021-03-16 15:52 UTC, tlhmerry9 commented
Accidentally merged this when resolving the conflict

2021-03-18 10:06 UTC, jirihnidek commented
> Accidentally merged this when resolving the conflict

Please, be more careful next time. Merged commit looks OK.

2021-03-19 13:16 UTC, tlhmerry9 commented
I will most definitely be more careful!

________________________________
From: Jiri Hnidek ***@***.***>
Sent: Thursday, March 18, 2021 5:07 AM
To: candlepin/subscription-manager ***@***.***>
Cc: tlhmerry9 ***@***.***>; State change ***@***.***>
Subject: Re: [candlepin/subscription-manager] 1637083: add unset sections (#2493)


Accidentally merged this when resolving the conflict

Please, be more careful next time. Merged commit looks OK.

—
You are receiving this because you modified the open/close state.
Reply to this email directly, view it on GitHub<https://github.com/candlepin/subscription-manager/pull/2493#issuecomment-801793153>, or unsubscribe<https://github.com/notifications/unsubscribe-auth/AHNY7EXZA4DIVTNA23KK5XLTEHGELANCNFSM4ZHD4NSA>.