1916540: Negative proxy tests occasionally encounter the wrong except…
candlepin/subscription-manager pull request #2509
Opened 2021-03-17 19:01 UTC by tlhmerry9

…ion handling

2021-03-18 10:32 UTC, jirihnidek requested changes
Hi,
Thanks for the PR. I can confirm that this change fixes the problem, but it breaks some unit tests. Please fix them. There are some stylish errors.

2021-03-18 10:32 UTC, jirihnidek commented on src/subscription_manager/cache.py
> +
Too many blank lines.

2021-03-22 17:45 UTC, tlhmerry9 commented
Fixed the tests related to this change.  

This is blocked by PR [#2479](https://github.com/candlepin/subscription-manager/pull/2479).   Once PR [#2479](https://github.com/candlepin/subscription-manager/pull/2479) is merged with master this branch needs to be rebased to master to resolve the test errors.

2021-03-29 17:58 UTC, tlhmerry9 commented on src/subscription_manager/cache.py
> +
done

2021-03-30 07:17 UTC, ptoscano commented on src/subscription_manager/cache.py
> +
extra empty line addition

2021-03-30 18:49 UTC, tlhmerry9 commented on src/subscription_manager/cache.py
> +
removed

2021-04-06 13:37 UTC, tlhmerry9 commented
@candlepin-bot ok to test

2021-04-06 13:37 UTC, tlhmerry9 commented
@candlepin-bot please retest this

2021-04-06 13:39 UTC, tlhmerry9 commented
all requested changes have been made

2021-04-12 10:05 UTC, jirihnidek approved these changes

2021-04-12 10:07 UTC, merged