cockpit: fix some unextracted & untranslatable strings
candlepin/subscription-manager pull request #2574
Opened 2021-04-14 07:48 UTC by ptoscano

- fix few untranslatable string in the cockpit plugin
- tweak a JS bit so other strings can actually be extracted by xgettext now

RHBZ: 1819555
Card ID: ENT-2265

2021-04-14 18:26 UTC, wottop commented
ack, when squashed to a single commit.

2021-04-14 18:27 UTC, wottop requested changes
needs to be squashed to a single commit

2021-04-14 18:38 UTC, ptoscano commented
> needs to be squashed to a single commit

hm why so?

2021-04-14 18:40 UTC, wottop commented
Aren't they all part of BZ 1819555. Our practice is to make a single commit for a single BZ where possible.

2021-04-15 13:33 UTC, wottop approved these changes

2021-04-15 13:33 UTC, wottop commented
ack

2021-04-15 13:33 UTC, merged