1744696: Fix issue with proxy and cockpit plugin
candlepin/subscription-manager pull request #2580
Opened 2021-04-15 13:23 UTC by jirihnidek

* BZ: https://bugzilla.redhat.com/show_bug.cgi?id=1744696
* When user decided to not use proxy in cockpit plugin despite
  some proxy settings are set in rhsm.conf, then cockpit
  plugin and rhsm.service still wanted to use proxy settings
  from rhsm.conf. This issue is fixed in this commit
* Added some unit tests
* Fixed few unit tests related to HTTP_PROXY env. var. for the
  case, when some proxy setting is in the /etc/rhsm.rhsm.conf
  on testing machine (unit tests tried to read this
  configuration file)

2021-04-19 14:35 UTC, ptoscano commented
The changes in cockpit/src/subscriptions-client.js seem fine to me.

The changes in src/rhsm/connection.py seem like code reformatting without any behaviour change?

The changes in test/rhsm/unit/connection_tests.py seem fine too; however I'd see them better an own change, rather than stuffed together with a cockpit bugfix.

2021-04-19 14:43 UTC, jirihnidek commented
> The changes in cockpit/src/subscriptions-client.js seem fine to me.
> 
> The changes in src/rhsm/connection.py seem like code reformatting without any behaviour change?

It could look like that, but it's not true. This code was wrong:

```python
            self.proxy_hostname = proxy_hostname or \
                                  config.get('server', 'proxy_hostname') or \
                                  info['proxy_hostname']
```

Why? When `proxy_hostname` was empty string, then this empty string was ignored and value from configuration file was used. When you do NOT want to use proxy setting and you use D-Bus API, then you do not have another option than set `proxy_*` arguments to empty strings. 

> The changes in test/rhsm/unit/connection_tests.py seem fine too; however I'd see them better an own change, rather than stuffed together with a cockpit bugfix.

It is related to this issue. I don't think that it is necessary to split this this PR to more PRs.

2021-04-19 16:32 UTC, ptoscano commented
> It could look like that, but it's not true. This code was wrong:
> 
> ```python
>             self.proxy_hostname = proxy_hostname or \
>                                   config.get('server', 'proxy_hostname') or \
>                                   info['proxy_hostname']
> ```
> 
> Why? When `proxy_hostname` was empty string, then this empty string was ignored and value from configuration file was used. When you do NOT want to use proxy setting and you use D-Bus API, then you do not have another option than set `proxy_*` arguments to empty strings.

Ah right, "true" vs `None`. What about the following change?
```diff
@@ -179,7 +179,7 @@ class BaseConnection(object):
         else:
             info = utils.get_env_proxy_info()
 
-            self.proxy_hostname = proxy_hostname or \
+            self.proxy_hostname = proxy_hostname is not None or \
                                   config.get('server', 'proxy_hostname') or \
                                   info['proxy_hostname']
             self.proxy_port = proxy_port or \
```
(and similar for the other variables)

> > The changes in test/rhsm/unit/connection_tests.py seem fine too; however I'd see them better an own change, rather than stuffed together with a cockpit bugfix.
> 
> It is related to this issue. I don't think that it is necessary to split this this PR to more PRs.

Weeell, strictly speaking is a fix to make the test suite more robust to the environment it runs on, not changing anything in the way the cockpit plugin works.

2021-04-19 16:43 UTC, ptoscano commented
> Ah right, "true" vs `None`. What about the following change?
> 
> ```diff
> @@ -179,7 +179,7 @@ class BaseConnection(object):
>          else:
>              info = utils.get_env_proxy_info()
>  
> -            self.proxy_hostname = proxy_hostname or \
> +            self.proxy_hostname = proxy_hostname is not None or \
>                                    config.get('server', 'proxy_hostname') or \
>                                    info['proxy_hostname']
>              self.proxy_port = proxy_port or \
> ```

Scratch this, as it will not do the same.

2021-05-04 18:54 UTC, tlhmerry9 approved these changes
LGTM - Leaving in Waiting on Review for someone else to approve

2021-05-07 06:36 UTC, ptoscano requested changes
As I mentioned in a previous comment, the changes themselves look OK; however, they need to be split in different commits, rather than lumping everything in a giant blob which is harder to review, to bisect, and eventually backport.

2021-05-11 09:32 UTC, merged