Slightly improve our container detection
candlepin/subscription-manager pull request #2611
Opened 2021-04-28 05:59 UTC by ptoscano

Assuming that a particualr directory was mounted in a container is not a strong way to detect whether we are running in a container. Check for well-known files of podman and docker first.

2021-04-28 14:26 UTC, cnsnyder commented on src/rhsm/config.py
> +    # we are running n a container
n -> in

2021-04-28 14:28 UTC, tlhmerry9 requested changes
shouldn't this be squashed?

2021-04-28 14:31 UTC, tlhmerry9 requested changes

2021-04-28 14:31 UTC, tlhmerry9 commented on src/rhsm/config.py
> +    # we are running n a container
typo

2021-04-28 14:38 UTC, ptoscano commented
> shouldn't this be squashed?

one commit is the no-op refactor, and the other adds the new paths

2021-04-28 14:48 UTC, tlhmerry9 approved these changes
LGTM

2021-04-28 20:12 UTC, cnsnyder commented
I think this will achieve more robust container detection but I think it is worth us syncing with the podman and buildah folks on whether there are any edge cases here we might be breaking by enhancing our detection in this way.

2021-05-03 11:14 UTC, jirihnidek reviewed
When others team will agree with this implementation, then it would be good to add some unit tests for this change.

2021-07-09 18:37 UTC, merged