1959048: improve wording for missing or empty syspurpose values
candlepin/subscription-manager pull request #2634
Opened 2021-05-20 15:34 UTC by ptoscano

Try to improve and make more coherent the messages for missing
syspurpose attributes in the current subscription, or for an empty list
of values available.

Updates commit f4d903a88422ee661dc66459305d993b892be91a.

2021-05-20 17:40 UTC, wottop requested changes

2021-05-20 17:40 UTC, wottop commented on src/subscription_manager/cli_command/abstract_syspurpose.py
> +                    print(_('Warning: This organization does not have any subscription that provides a system purpose "{attr}".  This setting will not influence auto-attaching subscriptions.').format
This organization does not have any subscriptions that provide a system ...

2021-05-20 17:40 UTC, wottop commented on src/subscription_manager/cli_command/abstract_syspurpose.py
> +            print(_('This organization does not have any subscription that provides a system purpose "{syspurpose_attr}.').format(syspurpose_attr=self.attr))
same comment as above

2021-05-20 18:52 UTC, tlhmerry9 approved these changes
LGTM

2021-05-24 15:53 UTC, jirihnidek approved these changes
ACK

2021-05-25 14:40 UTC, wottop approved these changes

2021-05-25 14:41 UTC, wottop commented
ack

2021-05-25 14:41 UTC, merged