1984133: repos: respect order of --enable & --disable
candlepin/subscription-manager pull request #2720
Opened 2021-08-03 05:56 UTC by ptoscano

With the old `optparse` implementation, there was a single callback to
fill `repo_actions` with the various values of the `--enable` & `--disable`
options, in the same order they were specified on the command line.
Commit eef1bb13f8924af9539f98330465c110f2df92b5 switched to `argparse`,
and switched to different destination lists for `--enable` & `--disable`,
mixing them back to a single list with first all the repos to enabled
and then all the repos to disable. As result, the order of intermixed
`--enable` & `--disable` was lost.

To revert back to the wanted behaviour, implement a custom
`argparse.Action` for `--enable` & `--disable` that appends all the actions to
the same list in the same order they were specified. This removes the
need for post-processing later on.

Card-ID: ENT-4146

2021-08-03 09:02 UTC, jirihnidek requested changes
Overall I like the PR. I have two small requests.

2021-08-03 09:02 UTC, jirihnidek commented on test/cli_command_test/test_repos.py
> +        self.check_output_for_repos_enabled_disabled(cap.out, repos_changes)
Can you please add here more tests cases for wildcards?  It should be easy.

2021-08-04 16:23 UTC, ptoscano commented on src/subscription_manager/cli_command/repos.py
> +    def __call__(self, parser, namespace, value, option_string=None):
I added something as doc string for `__call__()`, which IMHO should complement what the doc string of the `ReposAddRemoveAction` class says.

If not, can you please be a little more verbose on what to document/comment? It is fine for me, just need to know what is the doubt about :)

2021-08-05 08:37 UTC, jirihnidek approved these changes
Thanks for updates. It looks good now. :+1:

2021-08-05 08:37 UTC, jirihnidek commented on src/subscription_manager/cli_command/repos.py
> +    def __call__(self, parser, namespace, value, option_string=None):
I think that added doc string is enough. Thanks.

2021-08-05 08:39 UTC, merged