1922151: Use in-memory cache on AWS too
candlepin/subscription-manager pull request #2730
Opened 2021-08-11 10:52 UTC by jirihnidek

* BZ: https://bugzilla.redhat.com/show_bug.cgi?id=1922151#c5
* In-memory cache wasn't used properly
* All instances of BaseCloudProvider and subclasses are sinletons
  to be able to store in-memory cache easily. The code is not
  thread safe at this momement, because it is not necessary now.
  Making code thread safe will require more effort and it will
  be solved in different PR/commit.
* Fixed unit tests, because singleton is used
* Added unit test for singleton and using in-memory cache

2021-08-11 15:09 UTC, jirihnidek commented
I would like to test this PR more.

2021-08-16 18:52 UTC, cnsnyder commented on test/cloud_what/test_cloud_what.py
> +        Any subclass of VaseCloudProvider should behave as singleton
Vase -> Base

2021-08-16 18:53 UTC, cnsnyder requested changes
One small typo, other than that waiting on feedback from QE folks. I think it looks good.

2021-08-17 07:53 UTC, jirihnidek commented on test/cloud_what/test_cloud_what.py
> +        Any subclass of VaseCloudProvider should behave as singleton
Fixed.

2021-08-17 19:47 UTC, cnsnyder commented
We need a version of this targeted for subscription-manager-1.28 as well.
This being merged to the subscription-manager-1.28 branch blocks #2721 and #2735 
This also needs #2736

2021-08-17 19:47 UTC, cnsnyder approved these changes

2021-08-18 14:06 UTC, merged