1995465: Do not use deprecated collestions.MutableMapping
candlepin/subscription-manager pull request #2753
Opened 2021-08-23 10:09 UTC by jirihnidek

* BZ: https://bugzilla.redhat.com/show_bug.cgi?id=1995465
* The collestions.MutableMapping was deprecated in Python 3.3
  and new collestions.abc.MutableMapping should be used.
  The old API will be completely removed in Python 3.10.
* Fixed another similar issue with collections.Iterable
  in unit tests

2021-08-23 11:18 UTC, cnsnyder requested changes
Looks good to me other than a typo in the commit message "collestions" -> "collections". I think mergeable after that.

2021-08-25 13:01 UTC, jirihnidek commented
@cnsnyder friendly reminder: I updated the PR as you requested.

2021-08-25 13:16 UTC, ptoscano commented
> @cnsnyder friendly reminder: I updated the PR as you requested.

Hm I still see a "collestions" in the commit message, and two in the PR title/description.

2021-08-25 13:29 UTC, jirihnidek commented
@ptoscano fixed.

2021-08-25 13:38 UTC, ptoscano approved these changes
Typos fixed, so LGTM.

2021-08-25 13:38 UTC, merged