Translations update from Weblate
candlepin/subscription-manager pull request #2791
Opened 2021-09-17 13:04 UTC by weblate

Translations update from [Weblate](https://translate.fedoraproject.org/projects/subscription-manager/subscription-manager-main/) for subscription-manager/subscription-manager-main.

Current translation status:

![Weblate translation status](https://translate.fedoraproject.org/widgets/subscription-manager/-/subscription-manager-main/horizontal-auto.svg)

2021-09-20 09:10 UTC, jirihnidek requested changes
I can see some inconsistency how [OPTIONS] is handled in translated strings. My personal preference would be translated string (e.g. [VOLBY]).

2021-09-20 09:10 UTC, jirihnidek commented on po/ko.po
> +msgstr "%(prog)s {name} [OPTIONS] MANIFEST_FILE"
The translated string is replaced with `[OPTIONS]`.

2021-09-20 09:10 UTC, jirihnidek commented on po/ko.po
> +msgstr "%(prog)s {name} [선택(옵션)] "
Translated string is used here and `[OPTIONS]` is not used in this case.

2021-11-15 09:37 UTC, ptoscano approved these changes

2021-11-15 09:37 UTC, merged