1719690: Update to message formatting
candlepin/subscription-manager pull request #2867
Opened 2021-11-04 20:18 UTC by wottop

2021-11-05 12:03 UTC, ptoscano requested changes
Ideally, we'd fix things in `main` first, to avoid forgetting to forwardport them.

2021-11-05 16:49 UTC, wottop commented on src/subscription_manager/certlib.py
> +                buf += '-'.join(str(e).split('-')[1:]).strip()
Yes. Note that I also had to fix the case where there is no '-' in the error message.

2021-11-08 13:08 UTC, ptoscano requested changes
One more fixup, and it should be ok hopefully :)

I traced this back to when it was introduced, to know why it actually was done: I found commit 6c3a03f54c2e650fa7fd7f18d84f71aabdd75d89 for this, which unfortunately does not explain why the message had to be mungled that way...

2021-11-08 13:08 UTC, ptoscano commented on src/subscription_manager/certlib.py
> +                buf += ''.join(str(e).split('-', maxsplit=1)[1:]).strip()
considering that `split()` always returns a list, which in this case has either 1 (no '-') or 2 elements (`maxsplit=1`), then we can simplify this like this:
```python
    buf += str(e).split('-', maxsplit=1)[-1].strip()
```
no need for checking the character presence, and no need for `join()`

2021-11-09 13:16 UTC, ptoscano approved these changes
LGTM, thanks for the updates!

Please remember to forwardport it to `main`, to avoid losing it.

2021-11-09 13:17 UTC, merged