Set version of deb packages during build
candlepin/subscription-manager pull request #3020
Opened 2022-04-05 09:47 UTC by goarsna

Currently the version of subscription-manager isn't set during the build of the deb package. As a result the subscription-manager version is empty when running `subscription-manager version` on deb based systems.

As a first step **rpm-version** is refactored to **pkg-version** as the set version relates to both rpm and deb packages.

Secondly the version is passed to **make** in _contrib/debian/rules_ using **pkg-info.mk**.

2022-04-06 12:22 UTC, ptoscano requested changes
Hi @goarsna,

the changes seem OK at a first glance, I left few notes for minor things to fix. Also, there are flake8 issues and black issues:
```
src/rhsm/connection.py:43:1: W293 blank line contains whitespace
```
```diff
--- src/rhsm/connection.py	2022-04-06 12:11:38.606717 +0000
+++ src/rhsm/connection.py	2022-04-06 12:13:10.304814 +0000
@@ -38,11 +38,11 @@
 from rhsm import ourjson as json
 from rhsm import utils
 
 try:
     import subscription_manager.version
-    
+
     subman_version = subscription_manager.version.pkg_version
 except ImportError:
     subman_version = "unknown"
 
 config = get_config_parser()
would reformat src/rhsm/connection.py
--- test/test_api.py	2022-04-06 12:11:38.676717 +0000
+++ test/test_api.py	2022-04-06 12:13:15.794192 +0000
@@ -19,10 +19,11 @@
 
 
 class ApiVersionTest(SubManFixture):
     def test_version_is_available(self):
         from subscription_manager import version
+
         self.assertEqual(version.pkg_version, api.version)
 
 
 class RepoApiTest(SubManFixture):
     def setUp(self):
would reformat test/test_api.py
Oh no! 💥 💔 💥
2 files would be reformatted, 346 files would be left unchanged.
```

BTW: the Debian packaging in the sources is extremely outdated (e.g. still using Python 2), and it feels strange to me that it is used as it is... do you use it as it is, or use a more up-to-date/fresh packaging?

2022-04-06 12:22 UTC, ptoscano commented on contrib/debian/control
> +Build-Depends: debhelper (>= 9), dh-python, libglib2.0-dev, libdbus-glib-1-dev, libgtk2.0-dev, libglib2.0-dev, libgconf2-dev, libnotify-dev, lsb-release, pkg-config, python-all, python-setuptools, in
`dpkg-dev` is part of `build-essential`, so you don't need to pull it (unless you need a specific version of it, which is not the case here)

2022-04-06 12:22 UTC, ptoscano commented on contrib/debian/rules
> +include /usr/share/dpkg/pkg-info.mk
`default.mk` is included in the line before this, and already pulls all the other dpkg makefile scripts, including `pkg-info.mk` -- so the manual include is not needed (redundant)

2022-04-06 12:22 UTC, ptoscano commented on setup.py
> +        ("pkg-version=", None, "version and release of the RPM this is built for")
missed to change "RPM" in the description

2022-04-06 12:22 UTC, ptoscano commented on setup.py
> +            # When building the PKG there won't be a git repo to introspect so
i'd simply say "package" as normal word, to make it flow nicer in the comment

2022-04-07 07:43 UTC, goarsna commented
Hi @ptoscano,
I've implemented all your recommendations and also the tests with flake8 and black now passed.
Please let me know if there are any further recommendations / requirements. :)

Thanks!

2022-04-08 15:42 UTC, ptoscano approved these changes
Our CI is good with this, so let's pull it in.

Thanks!!

2022-04-08 15:42 UTC, merged

2022-04-11 08:18 UTC, goarsna commented
Hi @ptoscano,

thanks again for the fast merge!

Regarding the debian packaging: No problem :) a) The packaging instructions in the sources are for guidance and they are not used by us as is. b) Currently we support Debian >= 9 and Ubuntu >= 16.04. For the community we provide packages at https://apt.atix.de/ usually targeting the latest stable versions.

As soon as I get to update the packaging instructions in the sources I will open a PR. But if you want to rewrite the whole packaging instructions, feel free to go.