2043331: Do not delete installed SCA cert during registration
candlepin/subscription-manager pull request #3039
Opened 2022-04-22 16:36 UTC by jirihnidek

* Card ID: ENT-4726
* BZ: https://bugzilla.redhat.com/show_bug.cgi?id=2043331
* This issue happens really rarely, but it can be pretty confusing.
  When SCA entitlement has changed during registration, then it
  could lead to deleting installed SCA certificate. Why?
  The subscription-manager asks for the list of available SCA
  certificate. Candlepin server responses with the list of
  serial numbers. The subscription-manager ask for the
  entitlement certificate(s) and candlepin returns certs. Problem
  is that candlepin server returns SCA certificate despite
  requested serial number does not exists, because the SCA
  certificate has changed meanwhile. The subscription-manager
  later compares serial number of returned certificate and
  it deletes just installed SCA cert, because it is not in
  the original list.
* Fixed this issue and added more debug prints.

2022-04-22 16:39 UTC, jirihnidek commented
I need to figure out how to increase probability of this case to be able to do some real testing.

2022-04-24 07:20 UTC, unnecessary-username commented
Hello Jiri, 
    This is Tong He from the MPQE Entitlement QE team.
    A workaround I guess could increase the possibility is to add a new subscription (SKU) which introduces new Eng IDs to the existing SCA account. With the Stage account I shared with you, today I added a SKU which contains Eng ID 666 and then after a while I register it on RHSM and this issue appears again.
    I understand that account already covers most Eng IDs, but you may search for a SKU which contains Eng ID 547 in Ethel and add it to that account to have a try. Or another way is to create a new account in Ethel and consecutively add subscriptions to have a try.
Thanks,
Tong

2022-04-26 09:42 UTC, jirihnidek commented
Here is script that could be used for testing. This script uses infinity loop. So stop the script after testing. I tested this with organization `snowwhite` and this organization uses SCA mode. Maybe you will have to modify base URL of your candlepin server (`CANDLEPIN_SERVER`).

You will have to modify `POOL_ID` according your own candlepin server. You can obtain information about pools using:

```
curl --stderr /dev/null --insecure --user admin:admin \
    --request GET  https://<YOUR_CANDLEPIN>:8443/candlepin/owners/<YOUR_ORG>/pools/
```

```bash
#!/bin/bash

export CANDLEPIN_SERVER="https://localhost:8443/candlepin"
export POOL_ID="<YOUR_POOL_ID>"  # <====== Modify me!
export ORG_ID="snowwhite"
export TEMPLATE='{"id":"%s", "quantity":%d}'
export JSON_DOC='{}'

export QUANTITY=1
while :
do
	if [ $QUANTITY -lt 10 ];
	then
		QUANTITY=`expr ${QUANTITY} + 1`
	else
		QUANTITY=1
	fi
	echo "Generating JSON document..."
	JSON_DOC=`printf "$TEMPLATE" "$POOL_ID" "$QUANTITY"`
	echo $JSON_DOC > ./pool.json

	echo "JSON document: ${JSON_DOC}"

	echo "Changing quantity ${QUANTITY} of pool: ${POOL_ID} for group: ${ORG_ID}"

	curl --stderr /dev/null --insecure --user admin:admin --request PUT \
		--data @pool.json \
		--header 'accept: application/json' --header 'content-type: application/json' \
		${CANDLEPIN_SERVER}/owners/snowwhite/pools
	echo $?
done

```

I was able to reproduce this issue 100%, when I used main branch. When I used this feature branch, then I observed that this issue was fixed.

2022-04-26 09:46 UTC, jirihnidek commented
> Hello Jiri, This is Tong He from the MPQE Entitlement QE team. A workaround I guess could increase the possibility is to add a new subscription (SKU) which introduces new Eng IDs to the existing SCA account. With the Stage account I shared with you, today I added a SKU which contains Eng ID 666 and then after a while I register it on RHSM and this issue appears again. I understand that account already covers most Eng IDs, but you may search for a SKU which contains Eng ID 547 in Ethel and add it to that account to have a try. Or another way is to create a new account in Ethel and consecutively add subscriptions to have a try. Thanks, Tong

Hi Tong He,
Thanks for your recommendation, but we need more reliable reproducibility of this issue. It is possible to reproduce this issue almost 100% with the bash script that I provided. The admin access to candlepin is required, when this script is used. Thus it is possible to test it only with your own candlepin server.

Jiri

2022-05-10 09:39 UTC, jirihnidek commented
It is possible to test this with candlepin-3.x. This should not be issue, when candlepin-4.x is used, because serial number of certificates are not regenerated only content of certificate is regenerated.

2022-05-12 04:26 UTC, ptoscano requested changes
Seems OK at a first glance, however it requires a rebase.

2022-05-12 16:01 UTC, merged