Create singleton decorators in rhsm/utils.py
candlepin/subscription-manager pull request #3071
Opened 2022-06-14 15:39 UTC by m-horky

* Card ID: ENT-5054

Current implementation in rhsmlib/ combines singleton and lock
functionality, which makes it harder to separate those two.

This commit adds new functions that are used as decorators, instead of
classes that others will subclass.

This allows us to apply them only where they are needed, and test them
separately.

2022-06-15 12:29 UTC, ptoscano reviewed
A couple of notes for now, will continue later.

2022-06-15 12:29 UTC, ptoscano commented on src/rhsm/utils.py
> +            raise RuntimeError(f"Could not acquire call_once lock for function {fn.__name__}.")
hmm wouldn't it be better to acquire the lock as a context manager? this way it will be released automatically, and we can simplify the try later on

2022-06-15 14:54 UTC, ptoscano commented on src/rhsm/utils.py
> +            raise RuntimeError(f"Could not acquire call_once lock for function {fn.__name__}.")
Hmm the documentation for it says so though,
https://docs.python.org/3.6/library/threading.html#rlock-objects
"Reentrant locks also support the context management protocol."

2022-06-20 15:10 UTC, jirihnidek requested changes
I have few requests. I would like to know why you decided to drop class `Singleton` and why did you decide to use decorators instead?

2022-06-20 15:10 UTC, jirihnidek commented on src/rhsm/utils.py
> +    new = cls.__new__
I would use name `__orig_new` or something like this to emphasize that it is original __new__ method. It would be good to use type hint in this case.

2022-06-22 13:20 UTC, jirihnidek approved these changes
LGTM, thanks for updates.

2022-06-24 16:06 UTC, ptoscano requested changes
Thanks, it looks really nice now. I left few small notes for the tests, otherwise it is OK.

2022-06-27 12:07 UTC, ptoscano commented
hmm the cockpit test in rhel-8-7 always fails, I wonder whether this is causing any regression there...

2022-06-28 09:15 UTC, ptoscano approved these changes
Thanks! It looks good to me now.

2022-06-28 09:15 UTC, merged