2097679: Fixed script hang in non-interactive execution
candlepin/subscription-manager pull request #3148
Opened 2022-10-13 20:46 UTC by DuckBoss

- Resolved the script hanging issue caused by the script waiting on user inputs for information not specified through command line arguments by checking if the session is interactive and raising an error detailing the missing command line argument if not.
- Updated the man page "commands and options" section with a note to document this behavior.
- BZ: https://bugzilla.redhat.com/show_bug.cgi?id=2097679
- Card ID: ENT-5117

2022-10-18 13:36 UTC, ptoscano requested changes
it's a nice start, there are few things to improve; note i left comments in the first occurrence of each issue, so make sure to check the rest too

2022-10-18 13:36 UTC, ptoscano commented on man/subscription-manager.8
> +Please note that using commands that requires providing a username, password, organization, or environments will require them to be passed as system arguments in a non-interactive session.
s/requires/require/ (it refers to "commands", which is plural)

2022-10-18 13:36 UTC, ptoscano commented on man/subscription-manager.8
> +Please note that using commands that requires providing a username, password, organization, or environments will require them to be passed as system arguments in a non-interactive session.
i'd mention explicitly what are the affected options, e.g. "... providing an username using .B --username etc" (take care of the groff formatting); this makes it easier to see them, and to look/search for them

2022-10-18 13:36 UTC, ptoscano commented on src/subscription_manager/cli_command/register.py
> +            raise system_exit(os.EX_USAGE, "Error: --environments parameter not provided!")
`system_exit()` does not raise an exception, but directly causes sub-man to quit; hence, "raise" is not needed

2022-10-18 13:36 UTC, ptoscano commented on src/subscription_manager/cli_command/register.py
> +            raise system_exit(os.EX_USAGE, "Error: --environments parameter not provided!")
error messages shown to the user must be translatable; use the `gettext()` function, also usually available as `_()`

2022-10-18 13:36 UTC, ptoscano commented on src/subscription_manager/cli_command/register.py
> +            raise system_exit(os.EX_USAGE, "Error: --environments parameter not provided!")
regarding the text of the message: exclamation marks usually work for games, not in general messages; i'd also be more explicit on the actual reason why sub-man is erroring out, eg something like "--environments is required and it was not specified"

2022-10-18 13:36 UTC, ptoscano commented on src/subscription_manager/cli_command/register.py
> +        return sys.stdin and sys.stdin.isatty()
this is a good idea, however the same logic is duplicated in user_pass.py; hence, i'd move it to a more generic place such as src/subscription_manager/utils.py, with a more fitting name eg "is_interactive()"

2022-10-18 16:44 UTC, DuckBoss commented on src/subscription_manager/cli_command/user_pass.py
> +                )
Did you mean something like this and avoiding the grouped error message?

```python
if not username:
    system_exit(
        os.EX_USAGE, _("Error: --username is a required parameter and it was not provided.")
    )
if not password:
     system_exit(
        os.EX_USAGE, _("Error: --password is a required parameter and it was not provided.")
     )
```

2022-10-19 07:50 UTC, ptoscano commented on src/subscription_manager/cli_command/user_pass.py
> +                )
yeah, exactly

2022-10-20 12:53 UTC, DuckBoss commented on src/subscription_manager/cli_command/register.py
> +                os.EX_USAGE, _("Error: --environments is a required parameter and it was not provided.")
Thanks for your feedback. I will make those changes.

2022-10-20 14:45 UTC, jirihnidek approved these changes
LGTM

2022-10-24 14:49 UTC, ptoscano approved these changes
LGTM, thanks!

2022-10-24 14:49 UTC, merged

2022-10-24 16:06 UTC, ptoscano commented
Interesting bit I got by reviewing #3150: it does fix also `OrgCommand._get_org()`, which this PR didn't fix. Can you please create a followup PR for `main` for that?

2022-10-24 20:05 UTC, DuckBoss commented
> Interesting bit I got by reviewing #3150: it does fix also `OrgCommand._get_org()`, which this PR didn't fix. Can you please create a followup PR for `main` for that?

Thanks for finding this, I've set up a PR to address this: https://github.com/candlepin/subscription-manager/pull/3153