ENT-3759: Test on GitHub Actions
candlepin/subscription-manager pull request #3192
Opened 2023-01-16 14:02 UTC by m-horky

* Card ID: ENT-3759

2023-01-23 15:00 UTC, ptoscano requested changes
Looks like a good start!

I left some minor notes & questions here and there, nothing too problematic IMHO.

2023-01-24 19:05 UTC, jirihnidek requested changes
I like it! :+1: I have few comments notes and suggestions too.

2023-01-24 19:05 UTC, jirihnidek commented on .github/workflows/pytest.yml
> +            pytest_args: '--deselect test/rhsmlib/facts/test_hwprobe.py::HardwareProbeTest::test_networkinfo --deselect test/rhsmlib_test/test_facts.py::TestFactsDBusObject::test_GetFacts'
This class and method is located in the following file: `test/rhsmlib/dbus/test_facts.py`. If there is good reason to not run following unit tests, then this reason should be shared in the comment of the code.

2023-01-25 13:51 UTC, ptoscano commented on .github/workflows/pytest.yml
> +            pytest_args: '--deselect test/rhsmlib/facts/test_hwprobe.py::HardwareProbeTest::test_networkinfo --deselect test/rhsmlib_test/test_facts.py::TestFactsDBusObject::test_GetFacts'
though, if it worked in the first revision, then most likely the exclusion of `test_GetFacts` is not needed?

2023-01-25 13:54 UTC, ptoscano commented on .github/workflows/pytest.yml
> +            # The 'test_networkinfo' breaks in CentOS container because it has IPv6 disabled.
what I meant is something different:
https://github.com/candlepin/subscription-manager/blob/e9b945a1bb79a413a5271a2f74ed5d69848873ca/test/rhsmlib/facts/test_hwprobe.py#L581-L585
ie `test_networkinfo` requires that both `network.ipv4_address` and `network.ipv6_address` facts are available, which may not be the case if either is disabled

2023-01-25 13:54 UTC, ptoscano commented on test/rhsmlib/dbus/test_facts.py
> +        cls.patches["get_virt_info"].return_value = {}
ah sure, separate PR is what I had in mind -- waiting for it ;)

2023-01-25 14:03 UTC, ptoscano commented on .github/workflows/pytest.yml
> +            python3 -m pytest ${{ matrix.pytest_args }}
oh nice action, looking forward to it :+1:

2023-01-26 13:51 UTC, ptoscano approved these changes
LGTM, thanks!

I'll let Jirka review this as well, as he had notes previously.

2023-01-26 20:26 UTC, jirihnidek approved these changes
ACK

2023-01-26 20:26 UTC, merged