2132242: [1.28] Outsource uploading DNF profile to rhsmcertd
candlepin/subscription-manager pull request #3242
Opened 2023-04-04 12:30 UTC by jirihnidek

* Backport to 1.28 branch.
  * Original PR: #3139
  * Original commit: cc3f24c2107ccf0ed43026d7daceb5e533b8df8d
* BZ: https://bugzilla.redhat.com/show_bug.cgi?id=2132242
* Card ID: ENT-5530
* The subscription-manager tries to upload combined DNF profile at the end of registration process. Gathering of this profile can take very long time. It can be several minutes in some edge cases. This blocked registration process and the activity of gathering DNF profile was not communicated using live status message like other activities.
* This commit uses novel approach. The process of gathering and uploading of DNF process is outsourced to rhsmcertd service. The subscription-manager sends SIGUSR1 signal to rhsmcertd service to trigger gathering and uploading DNF profile. When rhsmcertd is not running, then old blocking approach is used, but this activity is communicated to user using live status message.
* The rhsmcertd can receive SIGUSR1 signal and it starts Python script package-profile-uploader, which is already part of installation.
* The information about rhsmcertd PID is written to lock file of rhsmcertd /var/lock/subsys/rhsmcertd
* When rhsmcertd is shutting down, then it tries to delete lock file
* glib functions are used for handling signals and spawning new process (only uploading of profile ATM).
* Updated some unit tests
* TODO:
  * Use same approach for DNF plugin subscription-manager

2023-04-17 16:02 UTC, jirihnidek commented on src/daemons/rhsmcertd.c
> +#if GLIB_MAJOR_VERSION <= 2 && GLIB_MINOR_VERSION < 58
Good point. I will fix it, when all other commits are back-ported.

2023-04-21 05:21 UTC, ptoscano requested changes
this is mostly OK, I think there are couple of fixups needed:
- regarding commit `2132242: [1.28] Outsource uploading DNF profile to rhsmcertd`:
  - this contains also the backport of commit b70c0d524675a0cb3b7971df56ffcb588ad52df6; can you please backport it as separate commit, so it's easier to review and to audit in the git history?
- regarding commit `rhsmcertd reads default_log_level from rhsm.conf`:
  - this contains also the backport of commit 3a8e42afb855f4f7378a862a0445348d14728b49; can you please backport it as separate commit, so it's easier to review and to audit in the git history?
- if I remember the testing that happened back then, I think you need to also backport commit 1bb1850325f9b157b8111e871e1193a33cd7b484 to avoid SELinux issues when `rhsm-package-profile-uploader` runs

2023-04-21 05:21 UTC, ptoscano commented
(and while you are there, please also rebase it, as there were other commits pushed to the 1.28 branch in the meanwhile)

2023-04-28 10:12 UTC, ptoscano approved these changes
LGTM -- the CI failure is `npm` crashing in Fedoraw Rawhide, which can be ignored for something targeted at RHEL 8.

2023-04-28 10:12 UTC, merged

2023-04-28 12:07 UTC, jirihnidek commented
Thanks :+1: