2060101: [1.24] Print correct status, when access mode has changed
candlepin/subscription-manager pull request #3261
Opened 2023-05-02 14:45 UTC by jirihnidek

* Backport two PRs to 1.24 branch. Original PRs:
  * https://github.com/candlepin/subscription-manager/pull/3049
    * Required some changes to make code Python 2 compatible
  * Part of this PR: https://github.com/candlepin/subscription-manager/pull/2321
* Card ID: ENT-5327

2023-05-03 05:32 UTC, ptoscano commented
Please rebase on top of the current 1.24 branch, so it gets the recent GitHub Action additions.

2023-05-10 08:59 UTC, jirihnidek commented
Hi @pinotree, FYI it is rebased

2023-05-16 15:44 UTC, ptoscano requested changes
Sorry for the late answer, testing things on el7 took me more time; it is generally OK, there are few things to tweak (I added inline comments); one more thing I cannot add an inline comment is:
In `ComplianceManager.load()` there is:
```python
        self.system_status = 'unknown'
```
As part of the changes of the backport of commit ad23dcf1fdab56fb03fae895a8d86d8f81c3a3da, this needs to be changed to
```python
        self.system_status = UNKNOWN
```

Thanks!

2023-05-16 15:44 UTC, ptoscano commented on src/subscription_manager/cert_sorter.py
> +        """
while adding comments is generally a good thing, this was not in the original commit

2023-05-23 14:36 UTC, jirihnidek commented
> ```python
> self.system_status = 'unknown'
> ```

Good catch! Thanks. I also noticed that `get_status_for_icon()` used strings ("invalid" and "partial").

2023-05-24 12:56 UTC, ptoscano approved these changes

2023-05-24 12:56 UTC, merged