Improve debug logging
candlepin/subscription-manager pull request #3361
Opened 2023-12-11 13:27 UTC by m-horky

This change clearly labels each section that's printed to make it easier to identify the interesting parts.

This also adds SUBMAN_DEBUG_PRINT_TRACEBACKS flag to print the traceback directly to stdout.

---

Example:

![image](https://github.com/candlepin/subscription-manager/assets/86803748/91c4562d-fbbe-42e8-b656-f96b8792318f)

2023-12-11 16:11 UTC, m-horky commented
Set to draft; `src/cloud_what/_base_provider.py` needs updating as well.

2023-12-11 17:12 UTC, m-horky commented
Question for the reviewer: would it be worth to define the colors on a single place? This code isn't updated often, and it is quite isolated, so maybe it is enough, as it has been for several years now.

2023-12-12 12:13 UTC, jirihnidek requested changes
Yeah, I would define colors on single place. Maybe it could be useful for other parts of code. We could make output of subscription-manager more colorful.

2023-12-12 12:13 UTC, jirihnidek commented on src/rhsm/connection.py
>                  + f"{normalized_host(self.host)}:{safe_int(self.ssl_port)}{handler} {request_type}"
If you are significantly changing debug printing, then please print `request_type` first to get something like this:

```
Request:
GET https://centos8-candlepin:8443/candlepin/ (using consumer auth)
```

2023-12-12 13:29 UTC, m-horky commented
Thanks. You are right, I discovered I even made local changes that did that, I forgot to finish it.

This is how it looks like now:

![image](https://github.com/candlepin/subscription-manager/assets/86803748/d8037c60-030a-4d24-b03e-9bf2a5b7034b)

2023-12-14 13:58 UTC, jirihnidek approved these changes
LGTM, Thanks for updates :+1:

2023-12-14 13:58 UTC, merged