Skip creating the yum.repos.d structure on debian based systems
candlepin/subscription-manager pull request #3369
Opened 2024-01-12 14:34 UTC by sbernhard

If you currently run "subscription-manager repos" on a debian/ubuntu system, the directory `/etc/yum.repos.d/` and the file `/etc/yum.repos.d/redhat.repo` with only the header are created. This is confusing some debian/ubuntu users. 

This patch does fix this behaviour.

2024-01-12 15:48 UTC, ptoscano commented
The changes in `init_repo_file_classes()` make sense to me.

As for the rest of the changes: it looks to me that the issue that triggers the addition of the option in `RepoFileBase` is the fact that `RepoActionInvoker` unconditionally uses `YumRepo`. Would you please provided a trace of the call stack that leads to the usage of `RepoActionInvoker` on debian-based systems? I'd rather fix that, than keep using a repo type (`YumRepo`) that does not belong to the current system.

2024-01-12 15:57 UTC, sbernhard commented
Sure. Thanks @pinotree for you answer.

If you run `subscription-manager repos` there are multiple sections:

```Create repo is called for /etc/yum.repos.d/redhat.repo
  File "/usr/sbin/subscription-manager", line 33, in <module>
    sys.exit(load_entry_point('subscription-manager==1.29.35', 'console_scripts', 'subscription-manager')())
  File "/usr/lib/python3/dist-packages/subscription_manager/scripts/subscription_manager.py", line 73, in main
    return managercli.ManagerCLI().main()
  File "/usr/lib/python3/dist-packages/subscription_manager/managercli.py", line 92, in main
    ret: Optional[int] = CLI.main(self)
  File "/usr/lib/python3/dist-packages/subscription_manager/cli.py", line 197, in main
    return cmd.main()
  File "/usr/lib/python3/dist-packages/subscription_manager/cli_command/cli.py", line 410, in main
    return_code = self._do_command()
  File "/usr/lib/python3/dist-packages/subscription_manager/cli_command/repos.py", line 141, in _do_command
    repos = rl.get_repos()
  File "/usr/lib/python3/dist-packages/subscription_manager/repolib.py", line 222, in get_repos
    yum_repo_file = YumRepoFile(options = ['skip_creating_repo'])
  File "/usr/lib/python3/dist-packages/rhsm/repofile.py", line 564, in __init__
    RepoFileBase.__init__(self, path, name, options)
  File "/usr/lib/python3/dist-packages/rhsm/repofile.py", line 371, in __init__
    self.create()
  File "/usr/lib/python3/dist-packages/rhsm/repofile.py", line 405, in create
    traceback.print_stack()
```

2024-01-12 17:28 UTC, ptoscano commented
So what if you replace the usage of `YumRepoFile` with `AptRepoFile` in `RepoActionInvoker` if `HAS_DEB822` is defined? In the end, I don't see how using `YumRepoFile` in a debian-based would be correct, TBH...

2024-02-02 14:03 UTC, sbernhard commented
Any thoughts on this PR @ptoscano ?

2024-02-02 15:47 UTC, ptoscano commented
One question I have is: on a Debian system **without** this patch, what do you get when running `subscription-manager repos`?

2024-02-02 15:56 UTC, sbernhard commented
/etc/yum.repos.d and a file red hat.repo containing the header.

2024-02-06 10:50 UTC, jtruestedt commented
Just to add - if you have rpm-repos in your Content View and run "subscription-manager repos", you might end up with repositories in redhat.repo causing other issues like breaking the package-profile-upload to katello

2024-02-16 13:08 UTC, sbernhard commented
Can you run the tests @ptoscano ?

2024-03-06 16:53 UTC, sbernhard commented
@jirihnidek Can you maybe give some feedback / start the tests?

2024-03-08 10:39 UTC, jirihnidek commented
@sbernhard I'm just testing/reviewing this PR.

2024-03-11 16:54 UTC, jirihnidek requested changes
Thanks for the PR. The file `/var/lib/rhsm/repo_server_val/redhat.repo` is still created, which could be still confusing. I have two also other requests, because you use wrong names of Python modules.

2024-03-11 16:54 UTC, jirihnidek commented on src/subscription_manager/repolib.py
> +    from rhsm.repofile import AptRepoFile
It is wrong name of Python module. It should be `from subscription_manager.repofile import AptRepoFile`.

2024-03-11 16:54 UTC, jirihnidek commented on src/subscription_manager/repolib.py
> +    from rhsm.repofile import ZypperRepoFile
Similar comment here... It is wrong name of Python module. It should be `from subscription_manager.repofile import ZypperRepoFile`.

2024-03-12 15:41 UTC, jirihnidek commented
> > Thanks for the PR. The file `/var/lib/rhsm/repo_server_val/redhat.repo` is still created, which could be still confusing. I have two also other requests, because you use wrong names of Python modules.
> 
> Yes, thats true. I thought, this repo_server_val is a "internal storage" which is required for the sub-man and not something a user would ever see.

Hmm, the code is wild. The file `/var/lib/rhsm/repo_server_val/redhat.repo` is still needed as "internal storage", but I would try to rename it to something like `/var/lib/rhsm/repo_server_val/rhsm.sources` to not look like an alien from Red Hat world. Thoughts?

2024-03-12 15:44 UTC, sbernhard commented
> > > Thanks for the PR. The file `/var/lib/rhsm/repo_server_val/redhat.repo` is still created, which could be still confusing. I have two also other requests, because you use wrong names of Python modules.
> > 
> > 
> > Yes, thats true. I thought, this repo_server_val is a "internal storage" which is required for the sub-man and not something a user would ever see.
> 
> Hmm, the code is wild. The file `/var/lib/rhsm/repo_server_val/redhat.repo` is still needed as "internal storage", but I would try to rename it to something like `/var/lib/rhsm/repo_server_val/rhsm.sources` to not look like an alien from Red Hat world. Thoughts?

Make sense in general. Maybe "a lot of things" need to be adapted because of tests etc. Should we rename this in a separete PR?

2024-03-14 08:31 UTC, jirihnidek commented
> > > > Thanks for the PR. The file `/var/lib/rhsm/repo_server_val/redhat.repo` is still created, which could be still confusing. I have two also other requests, because you use wrong names of Python modules.
> > > 
> > > 
> > > Yes, thats true. I thought, this repo_server_val is a "internal storage" which is required for the sub-man and not something a user would ever see.
> > 
> > 
> > Hmm, the code is wild. The file `/var/lib/rhsm/repo_server_val/redhat.repo` is still needed as "internal storage", but I would try to rename it to something like `/var/lib/rhsm/repo_server_val/rhsm.sources` to not look like an alien from Red Hat world. Thoughts?
> 
> Make sense in general. Maybe "a lot of things" need to be adapted because of tests etc. Should we rename this in a separete PR?

You are right. We can do that in another PR.

2024-04-09 19:35 UTC, sbernhard commented
> > > > > Thanks for the PR. The file `/var/lib/rhsm/repo_server_val/redhat.repo` is still created, which could be still confusing. I have two also other requests, because you use wrong names of Python modules.
> > > > 
> > > > 
> > > > Yes, thats true. I thought, this repo_server_val is a "internal storage" which is required for the sub-man and not something a user would ever see.
> > > 
> > > 
> > > Hmm, the code is wild. The file `/var/lib/rhsm/repo_server_val/redhat.repo` is still needed as "internal storage", but I would try to rename it to something like `/var/lib/rhsm/repo_server_val/rhsm.sources` to not look like an alien from Red Hat world. Thoughts?
> > 
> > 
> > Make sense in general. Maybe "a lot of things" need to be adapted because of tests etc. Should we rename this in a separete PR?
> 
> You are right. We can do that in another PR.

Is there something missing for this PR?

2024-05-24 07:44 UTC, sbernhard commented
@jirihnidek / @ptoscano  Any update for this?

2026-05-12 13:49 UTC, closed without merging