fix: 1.28 Add python-requests to the list of required RPMs
candlepin/subscription-manager pull request #3371
Opened 2024-01-17 09:13 UTC by jirihnidek

* Card ID: RHEL-11947
* RPM package python-requests was not required, but "requests" Python package is used by auto-registration code

2024-01-18 11:02 UTC, jirihnidek commented
@ptoscano FYI: PR updated

2024-01-18 11:02 UTC, ptoscano requested changes
Thanks for the rebase.

Please note that the CI changes are not needed: there is no need to get the sources as git repository, and if you notice #3372 then you can see things were fixed by that PR already. Hence, please drop the "fix: CI: setup git repository properly" commit.

2024-01-18 11:12 UTC, jirihnidek commented
As you can see in the following job there were issues related to the fact that directory created from downloaded compressed archive wasn't real git repository.

E.g. this job: https://github.com/candlepin/subscription-manager/actions/runs/7554710695/job/20568141363?pr=3371

```
fatal: Not a git repository (or any parent up to mount point /__w)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
```

I would keep this commit as part of this PR for this reason.

2024-01-18 12:19 UTC, ptoscano commented
> As you can see in the following job there were issues related to the fact that directory created from downloaded compressed archive wasn't real git repository.

As I said, the nosetest job does not really need the sources as git repository.

> E.g. this job: https://github.com/candlepin/subscription-manager/actions/runs/7554710695/job/20568141363?pr=3371
> 
> ```
> fatal: Not a git repository (or any parent up to mount point /__w)
> Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
> ```

IMHO that was another consequence of the failed pip installation.

> I would keep this commit as part of this PR for this reason.

I'm pretty sure there is no need for it -- again, see #3372.

2024-01-18 13:51 UTC, jirihnidek commented
> IMHO that was another consequence of the failed pip installation.

No, it wasn't.

2024-01-18 14:23 UTC, ptoscano commented
There should still be no need to have the sources as git repository, and both the build and the execution of the test suite do not need a git repository.

2024-01-19 12:34 UTC, ptoscano approved these changes
thanks!

2024-01-19 12:34 UTC, merged