feat: remove command 'redeem' from subscription-manager
candlepin/subscription-manager pull request #3418
Opened 2024-06-18 13:59 UTC by grunwmar

Code lines referencing or using	`redeem` command object were deleted. Associated files defining command `redeem` and test for it were removed.
Command	`redeem` was removed from bash auto completion and man pages.

**Steps to reproduce**
- Clone the repository and switch to the branch `feat/cct-242`
- Install `subscription-manager` according `INSTALL.md`
- Run according to `INSTALL.md` (no `redeem` command appears)
- run `man subscription-manager` (no `redeem` command appears)

2024-06-19 10:30 UTC, jirihnidek requested changes
Thanks for the PR. It looks good. I have only one small request.

2024-06-19 10:30 UTC, jirihnidek commented on man/subscription-manager.8
> -8. redeem
Please, just remove redeem command from the list. There will be lot of removals of commands. Lot of conflicts. We will fix numbers in final edit of man page.

2024-06-26 09:31 UTC, m-horky requested changes
Could you revert the numbering for items in the man page, as Jirka suggested? We'll do it in one go later.

Could you also please reference the ticket ID in commit message? It is useful to include this kind of information.

2024-07-09 11:19 UTC, m-horky approved these changes
LGTM

2024-07-09 12:02 UTC, ptoscano requested changes
This is generally good; there are few more references to "redeem" to remove from the man page:
- the "REDEEM OPTIONS" section, which can be removed altogether
- in the "DEPRECATED COMMANDS" section, the bit about "activate" that points to "redeem"; "activate" was removed long ago, and leaving the pointer to "redeem" would give a "broken" reference
- the "REDEEMING EXISTING SUBSCRIPTIONS" section, which can be removed altogether

Thanks!

2024-07-09 13:24 UTC, ptoscano commented
> in the "DEPRECATED COMMANDS" section, the bit about "activate" that points to "redeem"; "activate" was removed long ago, and leaving the pointer to "redeem" would give a "broken" reference

I just fixed that with #3429; the other bits need to be removed.

Also, the reference to the card must be fixed: it is CCT-424, not CCT-242.

2024-08-28 12:53 UTC, ptoscano commented
Obsoleted by #3446, which was based on this.

2024-08-28 12:53 UTC, closed without merging