feat: remove command 'remove' from subscription-manager
candlepin/subscription-manager pull request #3419
Opened 2024-06-18 14:01 UTC by grunwmar

Code lines referencing or using	`remove` command object were deleted. Associated files defining command `remove` and test for it were removed.
Command	`remove` was removed from bash auto completion and man pages.

**Steps to reproduce**
- Clone the repository and switch to the branch `feat/cct-246`
- Install `subscription-manager` according `INSTALL.md`
- Run according to `INSTALL.md` (no `remove` command appears)
- run `man subscription-manager` (no `remove` command appears)

CARD ID: CCT-246

2024-06-19 10:35 UTC, jirihnidek requested changes
Unit tests are failing. You also have to remove file `./test/test_remove.py`

2024-06-19 10:35 UTC, jirihnidek commented on man/subscription-manager.8
> -5. remove
Same comment here. Please, jut remove `remove` command from the list and do not change numbers of other commands. We will fix this later.

2024-06-21 08:41 UTC, jirihnidek commented
Note: It will be also necessary to remove "Remove*" D-Bus methods from `rhsm.service`, but it should be done in another PR and it should be done by some more experience sub-man developer.

2024-07-15 08:47 UTC, ptoscano requested changes
The changes seem good to me, with a couple of extra minor notes; there are conflicts due to other changes that went in in the meanwhile, so please rebase this PR to the current `main`.

Also, since there are changes to do: please fix the "Assocciated" typo in the commit message.

Thanks!

2024-07-15 08:47 UTC, ptoscano commented on man/subscription-manager.8
> +.B --environments
note those whitespace changes are unrelated to the change; if would it be possible to avoid them, please do

2024-07-15 08:47 UTC, ptoscano commented on man/subscription-manager.8
> +.B --environments
ditto (extra whitespace changes)

2024-07-15 08:47 UTC, ptoscano commented on man/subscription-manager.8
> +is
ditto (extra whitespace changes)

2024-09-08 14:25 UTC, ptoscano commented
Obsoleted by #3444, which was based on this.

2024-09-08 14:25 UTC, closed without merging