Collect Azure VM Name and Resource Group Name as a cloud fact.
candlepin/subscription-manager pull request #3433
Opened 2024-07-31 17:26 UTC by chambridge

* Obtain the VM Name from the instance metadata API
* Obtain the Resource Group Name from the instance metadata API
* These items will improve deduplication logic within Subscription Watch metering

2024-07-31 17:27 UTC, chambridge commented
FYI - @barnabycourt @kahowell

2024-08-01 13:12 UTC, jirihnidek requested changes
Thanks for PR, I have only small request.

2024-08-01 13:15 UTC, jirihnidek commented
/packit build

2024-08-01 14:22 UTC, chambridge commented on test/rhsmlib/facts/test_cloud_facts.py
> +AZURE_RESOURCE_GROUP_NAME = "foo-bar"
done.

2024-08-01 15:02 UTC, jirihnidek approved these changes
Thanks for the PR. LGTM

2024-08-01 15:02 UTC, merged