fix: Restart rhsm service after installation
candlepin/subscription-manager pull request #3485
Opened 2024-12-18 14:36 UTC by pkoprda

* Card ID: CCT-1027

Following the installation of the subscription-manager package, the dbus service was not loaded as expected. This update addresses the problem by ensuring that the dbus service is properly restarted after the installation or upgrade process.

2024-12-18 17:07 UTC, pkoprda commented
I am not sure about the failing test :crying_cat_face:. However, here is a setup how you can test this change: 
1. Build RPM package from this commit (e.g. by using [tito](https://github.com/rpm-software-management/tito)) - `tito build --rpm --test` - at least for me the RPM package was saved as `/tmp/tito/subscription-manager-1.30.2-1.git.35.55c06d2.fc40.x86_64.rpm`

2. Upgrade subscription-manager package - `dnf upgrade /tmp/tito/x86_64/subscription-manager-1.30.2-1.git.35.55c06d2.fc40.x86_64.rpm`
3. Then you can use the script `get-environments.sh` from [jirihnidek/rhsm-dbus-examples](https://github.com/jirihnidek/rhsm-dbus-examples) repository (needs `library.sh`) to test this change:

```bash
#!/bin/bash

source ./library.sh

start_register_server
export username="admin"
export password="admin"
export org_id="content-sources-test"

echo "Trying to get list of organizations using dbus-send..."
dbus-send --address=${my_addr} --print-reply --dest='com.redhat.RHSM1.Register' \
       '/com/redhat/RHSM1/Register' \
       com.redhat.RHSM1.Register.GetEnvironments string:${username} \
       string:${password} \
       string:${org_id} \
       dict:string:string:"","" \
       string:""


stop_register_server
```

2024-12-18 20:29 UTC, jirihnidek commented on subscription-manager.spec
> +    systemctl restart rhsm.service
Why do you call `systemctl restart rhsm.service`? Why the macro `%systemd_post rhsm.service` is not enough?

2025-01-09 15:47 UTC, ptoscano requested changes

2025-01-09 15:47 UTC, ptoscano commented on subscription-manager.spec
> +    systemctl restart rhsm.service
Reference of the RPM macros: https://github.com/systemd/systemd/blob/46f881e32127cce03118dcd0471ded12d08d50b2/src/rpm/macros.systemd.in

`%systemd_post` in practice only installs the new service, and it does not do anything more than that

What seems to be needed here is `%systemd_postun_with_restart`, which seems to be marking the unit as "needs to be restarted", and then the rpm file triggers will make systemd restart the units marked as "no be restarted". Please note that the right place for that is in `%postun`, not `%post`.

2025-01-14 18:23 UTC, ptoscano requested changes
Thanks for the update!

The new macro does the trick, however only when the package with the scriptlet is removed, either because of uninstallation or upgrade. This means that when upgrading from a sub-man without this change to a sub-man with this change `rhsm.service` will not be restarted, since only the `%preun` of the already installed sub-man (i.e. that one without this change) is run.

As references to the RPM scriptlets, in particular the sections for syntax and ordering:
- https://docs.pagure.org/packaging-guidelines/Packaging%3AScriptlets.html
- https://docs.fedoraproject.org/en-US/packaging-guidelines/Scriptlets/

What I think we need here is to do the restart in `%posttrans`; according to the RPM macros for systemd (see the link I mentioned in my previous comment), `%systemd_posttrans_with_restart` should do it, and that needs to be placed in the `%posttrans` section.

2025-01-15 10:55 UTC, ptoscano commented
> I am not sure about the failing test 😿.

The C10S job was fixed after #3495, so make sure to rebase.

2025-01-17 05:46 UTC, ptoscano approved these changes
Upgrade scenarios I tested:

1. old package installed, `rhsm.service` not running, upgrading to the fixed package:
   - `rhsm.service` remains not running
   - -> PASS :+1: 

1. old package installed, `rhsm.service` running, upgrading to the fixed package:
   - `rhsm.service` is properly restarted
   - -> PASS :+1: 

1. fixed package installed, `rhsm.service` not running, reinstalling the fixed package (to simulate an upgrade from the fixed package as installed version):
   - `rhsm.service` remains not running
   - -> PASS :+1: 

1. fixed package installed, `rhsm.service` running, reinstalling the fixed package (to simulate an upgrade from the fixed package as installed version):
   - `rhsm.service` is properly restarted
   - -> PASS :+1: 

So IMHO everything works as expected, thanks!

The build failures on Fedora Rawhide are unrelated, and will be addressed separately.

2025-01-17 05:48 UTC, merged