integration tests for register with activation keys and environments
candlepin/subscription-manager pull request #3487
Opened 2024-12-31 06:08 UTC by jstavel

Card-ID: CCT-1051

A DBus API provides  a way to specify environment when using activation keys to register a system.

This PR provides integration tests to verify the way.

I've fixed a file 'integration-tests/README.md' - there were wrong activation keys specified.
It will be necessary to merge the fix into previous PR's that has something to do with activation keys.

A test:

Given a DBus Call RegisterWithActivationKeys is used to register a system
and the system is unregistered

When an argument 'environments' is filled with the proper environments
Then the application registers the system
and the environments are active property of a system identity.

Another test verifies a case when nonexisting environment is used for registration.

2025-01-10 14:07 UTC, jirihnidek commented
/packit build

2025-07-17 11:26 UTC, jirihnidek requested changes
Thanks for the PR, I have few requests.

2025-07-17 11:26 UTC, jirihnidek commented on integration-tests/pytest.ini
> +log_level = INFO
Same comment as in another PR, why you decreased log level?

2025-07-17 11:26 UTC, jirihnidek commented on integration-tests/test_register_with_activation_keys.py
> +        assert subman.is_registered
Why you changed this? It seems that it is not related to adding new test. It is also not described in commit log nor PR.

2025-07-17 11:26 UTC, jirihnidek commented on integration-tests/test_register_with_activation_keys.py
> +        ), "DBus method returns what activation keys were used to register a system"
The assertions error message should say what is wrong, when `assert()` is false. Something like: `D-Bus method 'RegisterWithActivationKeys' returned object that does not contain 'activationKeys'`.

2025-07-17 11:26 UTC, jirihnidek commented on integration-tests/test_register_with_activation_keys.py
> +        )
I would first call `response = private_proxy.RegisterWithActivationKeys()` and then I would parse response with `json.loads()`. It would improve readability and split potential issues.

2025-07-17 11:26 UTC, jirihnidek commented on integration-tests/utils.py
> +    """
The doc string has to be placed immediately after the method name. There cannot be anything else. The doc string should explain what the method does.

2025-07-17 11:26 UTC, jirihnidek commented on integration-tests/test_register_with_activation_keys.py
> +        assert pairs["environment name"] == first(candlepin_config("environment", "names"))
You test here output of `subscription-manager identity`. It is also possible, but you should test here that returned object contains environments from `candlepin_config("environment", "names")`

2025-07-31 12:51 UTC, jstavel commented on integration-tests/pytest.ini
> +log_level = INFO
moved back

2025-07-31 12:54 UTC, jstavel commented on integration-tests/test_register_with_activation_keys.py
> +        assert subman.is_registered
removed assert message. a reason of failure is obvious without the message too.

2025-07-31 13:04 UTC, jstavel commented on integration-tests/test_register_with_activation_keys.py
> +        ), "DBus method returns what activation keys were used to register a system"
changed

2025-07-31 20:22 UTC, jstavel commented on integration-tests/utils.py
> +    """
added docstring with a short description a method does.
changed a way to comment the region above

2025-07-31 20:27 UTC, jstavel commented on integration-tests/test_register_with_activation_keys.py
> +        assert pairs["environment name"] == first(candlepin_config("environment", "names"))
the assertation verifies that environment was applied - ie. dbus method set it in a system.
and subscription-manager is an independent way to verify a system has the environment.

I will add another assertation to verify that response provides the given environment back

2025-07-31 23:09 UTC, jstavel commented on integration-tests/test_register_with_activation_keys.py
> +        assert pairs["environment name"] == first(candlepin_config("environment", "names"))
added additional assertations

2025-08-13 14:32 UTC, jirihnidek approved these changes
Thanks for the update. LGTM now

2025-09-08 19:09 UTC, jstavel commented
I have rebased the branch. thank you.

2025-09-19 09:50 UTC, merged